import streamlit as st
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io

# ऐप कॉन्फ़िगरेशन
st.set_page_config(
    page_title="Trikaal Kundli - त्रिकाल कुंडली", 
    page_icon="🕉️",
    layout="centered"
)

# हेडर सेक्शन
st.title("🕉️ Trikaal Kundli (त्रिकाल कुंडली)")
st.caption("भूत, वर्तमान और भविष्य — आपकी जन्मपत्री का संपूर्ण विश्लेषण")
st.markdown("---")

# यूजर इनपुट फॉर्म
with st.form("trikaal_form"):
    st.subheader("अपनी जन्म जानकारी दर्ज करें")
    
    name = st.text_input("पूरा नाम (Full Name)")
    
    col1, col2 = st.columns(2)
    with col1:
        dob = st.date_input("जन्म तिथि (Date of Birth)")
    with col2:
        tob = st.time_input("जन्म समय (Time of Birth)")
        
    place = st.text_input("जन्म स्थान (Birth Place)", placeholder="जैसे: New Delhi, India")
    
    submit_button = st.form_submit_button(label="🔮 त्रिकाल कुंडली जनरेट करें")

# PDF जनरेशन फंक्शन
def create_trikaal_pdf(name, dob, tob, place):
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    
    # PDF डिज़ाइन और हेडर
    p.setFont("Helvetica-Bold", 22)
    p.drawString(180, 750, "TRIKAAL KUNDLI REPORT")
    p.setStrokeColorRGB(0.8, 0.2, 0.2)
    p.line(50, 735, 550, 735)
    
    # विवरण
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, 700, "Birth Details:")
    
    p.setFont("Helvetica", 11)
    p.drawString(70, 680, f"Name: {name}")
    p.drawString(70, 660, f"Date of Birth: {dob.strftime('%d-%m-%Y')}")
    p.drawString(70, 640, f"Time of Birth: {tob.strftime('%H:%M')}")
    p.drawString(70, 620, f"Place of Birth: {place}")
    
    p.line(50, 600, 550, 600)
    
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, 570, "Astrological Prediction (Trikaal Analysis):")
    p.setFont("Helvetica", 10)
    p.drawString(70, 540, "1. Past (Bhoot Kaal): Foundation & Root Chart")
    p.drawString(70, 520, "2. Present (Vartaman Kaal): Current Dasha & Planetary Transit")
    p.drawString(70, 500, "3. Future (Bhavishya Kaal): Future Guidance & Predictions")
    
    p.setFont("Helvetica-Oblique", 9)
    p.drawString(180, 50, "Generated by Trikaal Kundli Engine")
    
    p.showPage()
    p.save()
    buffer.seek(0)
    return buffer

# फॉर्म प्रोसेस
if submit_button:
    if not name or not place:
        st.warning("⚠️ कृपया नाम और जन्म स्थान दोनों भरें।")
    else:
        st.success(f"✨ {name} जी, आपकी 'त्रिकाल कुंडली' सफलतापूर्वक तैयार हो गई है!")
        
        pdf = create_trikaal_pdf(name, dob, tob, place)
        
        st.download_button(
            label="📥 डाउनलोड करें - Trikaal Kundli PDF",
            data=pdf,
            file_name=f"Trikaal_Kundli_{name}.pdf",
            mime="application/pdf"
        )
